name: Tag test
on:
  push:
    branches:
      - main
jobs:
  go-tests:
    name: Run Go Tag Tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup terraform  
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Setup SSH Key'
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Go modules setup
        working-directory: /test
        run: go get -v -t -d ./... && go mod tidy
        
      - name: Run Go Tests
        working-directory: /test
        run: go test -v

