name: Tag test
on: push
jobs:
  go-tests:
    name: Run Go Tag Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.15
      - uses: hashicorp/setup-terraform@v1
      - name: Download Go Modules
        working-directory: test
        run: go get -v -t -d && go mod tidy
      - name: Run Go Tests
        working-directory: test
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
