name: Tag test
on:
  push:
    branches:
      - main
jobs:
  go-tests:
    environment: Terratest
    name: Run Go Tag Tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Allow insecure commands in actions
          run:|
            echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup terraform  
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Setup SSH Key'
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - name: Go modules donwload
        working-directory: test
        run: go mod download
        
      - name: Run Go Tests
        working-directory: test
        run: go test -v

